### PR TITLE
Updated protobuf to v1.5.8

### PR DESCRIPTION
**Pull request by madelinegordon**
### Issue describing the changes in this PR

[Release v1.5.8](https://github.com/Azure/azure-functions-language-worker-protobuf/releases/tag/v1.5.8-protofile)

Related to changes for #912.

### Pull request checklist

* [ ] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
  * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Review by liliankasem — APPROVED** [review]

**Comment by liliankasem** [comment]
@madelinegordon any idea why it might be failing? or just flaky?

**Comment by madelinegordon** [comment]
> @madelinegordon any idea why it might be failing? or just flaky?

I hadn't changed the csharpnamespace value to reflect the worker rather than the host!

**Pull request merged**
