### PR TITLE
update net48

### LINKED ISSUE #1235: Stop using dotnet 4.72 in favor of dotnet 4.8
SDK still is compile against `net472`

```
<TargetFrameworks>netstandard2.0;net472</TargetFrameworks>
```
Azure Function officially only supports `net48`, therefore it would be opportunistic to upgrade to this version of the .net framework.

This does not produce any breaking change.

### PR DESCRIPTION
**Pull request by bobbyangers**
update net472 to >> net48

### Issue describing the changes in this PR

resolves #1235 

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
  * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Comment by bobbyangers** [comment]
Hi @fabiocav,  I have rebase this proposal.

**Comment by jviau** [comment]
@bobbyangers can you justify the need for moving to `net48`? What scenario is it unblocking / fixing?

**Comment by bobbyangers** [comment]
> @bobbyangers can you justify the need for moving to `net48`? What scenario is it unblocking / fixing?

Referring to [Azure Functions runtime versions overview](https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=v4&pivots=programming-language-csharp#languages), only .NET 4.8 is supported.

I simply suggest to migrate the SDK project to use the supported TFM.

**Comment by bobbyangers** [comment]
I am trying to contribute to your project by improving the support for supported TFM.

IMO, a usful package like this one should strive to use supported TFM, and retire code and DLL that use obsolete and unsafe DLL.

Clearly you don't support the method or the timing or something.

I'll widthdraw my PR and focus my energy on other projects.

**Pull request closed without merging**
