### PR TITLE
Add global.json to pin dotnet SDK

### LINKED ISSUE #1769: Engineering: pin dotnet SDK via global.json
Part of #1655

This issue tracks the work to leverage [global.json](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json), which lets us pin the dotnet SDK for all projects in the repo. This will give us the following benefits:

1. Consistent SDK version - for all devs and CI builds.
    - Without pinning the SDK, dotnet picks up the newest SDK installed. This leads to a dev will start seeing new language features being suggested by the editor. But then when they use and push, CI fails because it uses an older SDK.
2. Can leverage `UseDotnet` task in ADO. Simplifies having the CI build pick up newer sdks as we update `global.json`.

### PR DESCRIPTION
**Pull request by jviau**
### Issue describing the changes in this PR

resolves #1769

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
  * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests) -- none required

### CODE REVIEW

**Comment by liliankasem** [comment]
> Azure Pipelines could not run because the pipeline triggers exclude this branch/path.

SAD

**Review by kshyju — APPROVED** [review]

**Comment by jviau** [comment]
> > Azure Pipelines could not run because the pipeline triggers exclude this branch/path.
> 
> SAD

haha let me switch to a branch instead of a fork

**Pull request closed without merging**
