### PR TITLE
Initial CosmosDB.Mongo support

### PR DESCRIPTION
**Pull request by jaliyaudagedara**
### Issue describing the changes in this PR

resolves #issue_for_this_pr

### Pull request checklist

* [ ] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
  * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Comment by fabiocav** [comment]
@jaliyaudagedara thank you for the contribution!

Although some of the worker extensions live in this repo, more recent extensions are maintained in the same repositories as their WebJobs extension counterparts (e.g., SQL, OpenAI, etc.) and the plan is to move the extensions we currently have in this repo to align with that approach.

Can you please work with the team to have this change added to the appropriate repo [here](https://github.com/Azure/azure-functions-cosmosdb-extension)?

It would be good to start with an issue to make sure they have all the context.

**Comment by jaliyaudagedara** [comment]
@fabiocav 

Yeah, that makes more sense.

Of course, will do.

**Comment by jaliyaudagedara** [comment]
@fabiocav 

I am sorry for troubling you, https://github.com/Azure/azure-functions-cosmosdb-extension doesn't seem to be actively maintained. I had a [PR](https://github.com/Azure/azure-functions-cosmosdb-extension/pull/16) open for a while, but there was no response.

And now saw this issue:
[#12](https://github.com/Azure/azure-functions-cosmosdb-extension/issues/12)

Is there anyone you can contact internally, please?

I'd very much appreciate it.

**Comment by fabiocav** [comment]
@jaliyaudagedara we're working to track that down. If the core package is not currently maintained, that's another reason for us to avoid opening a PR taking a dependency on it until there's better support.

There's an email thread I believe you're on, and we'll continue following up on that.

**Comment by jaliyaudagedara** [comment]
Thanks @fabiocav, much appreciated!

Yeah, saw the email email thread. Let's follow up there.

Thanks again!

**Pull request closed without merging**
