### PR TITLE
Remove documentation tag

### PR DESCRIPTION
**Pull request by vanillajonathan**
The parameter does not exist.

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
  * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Review by jviau — APPROVED** [review]

**Comment by satvu** [comment]
@vanillajonathan can you merge main into your branch? [This change](https://github.com/Azure/azure-functions-dotnet-worker/commit/97e7048bf26b7da6d159a2c9143f42f8f91a7ef9) needs to be present to run the pipeline correctly. Thanks for the contribution!

**Comment by vanillajonathan** [comment]
@satvu done

**Comment by fabiocav** [comment]
Thank you, @vanillajonathan

**Pull request merged**
