### PR TITLE
Add RabbitMQ option to disable certificate validation

### LINKED ISSUE #1351: Option to disable RabbitMQ certificate validation
Can the `DisableCertificateValidation` option that is present in the `Microsoft.Azure.WebJobs.Extensions.RabbitMQ` be added to this library?

See https://github.com/Azure/azure-functions-rabbitmq-extension#c-attributes

### PR DESCRIPTION
**Pull request by ysbakker**
### Issue describing the changes in this PR

resolves #1351 

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
  * [x] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Comment by ysbakker** [comment]
@microsoft-github-policy-service agree

**Review by JatinSanghvi — COMMENTED** [review]
Please also add this property to the RabbitMQOutputAttribute class to have consistency. Were you able to disable certificate validation in your function app after making this change?

**Comment by ysbakker** [comment]
> Please also add this property to the RabbitMQOutputAttribute class to have consistency. Were you able to disable certificate validation in your function app after making this change?

Good point, I added the property to the output attribute as well. And yes, I was able to disable certificate validation by adding this property locally.

**Review by JatinSanghvi — APPROVED** [review]

**Comment by YoupHulsebos** [comment]
@JatinSanghvi thanks for your quick approval. Can you give me any perspective what the cycle time is before this change is included in a new stable nuget package? And is there any way we can help get this change there?

**Comment by JatinSanghvi** [comment]
> Can you give me any perspective what the cycle time is before this change is included in a new stable nuget package? And is there any way we can help get this change there?

@kshyju, can you give an ETA on when a NuGet package version with the change will get released?

**Comment by kshyju** [comment]
> > Can you give me any perspective what the cycle time is before this change is included in a new stable nuget package? And is there any way we can help get this change there?
> 
> @kshyju, can you give an ETA on when a NuGet package version with the change will get released?

We need the [version](https://github.com/Azure/azure-functions-dotnet-worker/blob/2b78e7b03503f499ae71507b2a842d1848b86fb2/extensions/Worker.Extensions.RabbitMQ/src/Worker.Extensions.RabbitMQ.csproj#L9) bumped for a new package version release.  I also noticed that Microsoft.Azure.WebJobs.Extensions.RabbitMQ 2.0.3 is also out  but the worker is still [using 2.0.0](https://github.com/Azure/azure-functions-dotnet-worker/blob/2b78e7b03503f499ae71507b2a842d1848b86fb2/extensions/Worker.Extensions.RabbitMQ/src/Properties/AssemblyInfo.cs#L6)

I think we could [point to in 2.0.3 Worker.Extensions.RabbitMQ](https://github.com/Azure/azure-functions-dotnet-worker/blob/2b78e7b03503f499ae71507b2a842d1848b86fb2/extensions/Worker.Extensions.RabbitMQ/src/Properties/AssemblyInfo.cs#L6) and include change from this PR and bump our version to 2.0.3 and publish that. Thoughts @JatinSanghvi ?

**Comment by JatinSanghvi** [comment]
Sounds good @kshyju. I have created #1365.

**Comment by YoupHulsebos** [comment]
Thanks for you quick response @JatinSanghvi. Your suggestion sounds great. Please let me know if I can help in any way.

The pipeline guarding this merge seems to be pending on a new permission. Who can approve this?

**Comment by JatinSanghvi** [comment]
> The pipeline guarding this merge seems to be pending on a new permission. Who can approve this?

@kshyju, can you merge the PR if it looks good?

**Comment by kshyju** [comment]
Thanks @JatinSanghvi for merging #1365. 
@ysbakker Could you rebase please?

**Comment by ysbakker** [comment]
@kshyju done!

**Review by kshyju — APPROVED** [review]

**Comment by kshyju** [comment]
Thanks for your contribution @ysbakker  🎉

Will share an update to this thread when the new version is published to nuget gallery.

**Comment by ysbakker** [comment]
> Thanks for your contribution @ysbakker 🎉
> 
> Will share an update to this thread when the new version is published to nuget gallery.

Awesome @kshyju 😄

I was curious if there are any updates?

**Comment by kshyju** [comment]
@v-shenoy Can you help with releasing this version?

**Comment by kshyju** [comment]
https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.RabbitMQ/2.0.3 is out.

**Pull request merged**
