### PR TITLE
Setup test framework

### LINKED ISSUE #281: Implement test worker/test framework
Implement a test worker and test helpers for public consumption.

This should also be adopted by the worker tests in the project.

### PR DESCRIPTION
**Pull request by bhugot**
### Issue describing the changes in this PR
It's an initial work with a few changes that would allow to tests Isolated Functions the same way we do it for in process function 

resolves #281

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
  * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Comment by bhugot** [comment]
Hello it's not finished for me but any feedback would be great.

**Comment by fabiocav** [comment]
@bhugot given the size/scope of the changes, can we please share more context about it in the issue we have tracking this feature (#281) so the rest of the team can collaborate on the design, goals and ensure we iterate on the approach before moving further with the changes? @brettsam also had an initial design and implementation, so it would be good to get his feedback to compare the approaches

**Comment by bhugot** [comment]
@fabiocav if my move is too big for you I think that I could split up a bit now by first allowing to using http client factory to create the Grpc Client and in a second one implement Test server Project?

**Comment by Qualizorg** [comment]
Would be great to have this evaluated @fabiocav @brettsam @kshyju

**Comment by fabiocav** [comment]
@bhugot this looks great, but it does take a significantly different approach than what we were originally planning with @brettsam's changes, which used the existing extensibility points to inject a test worker and use an in-memory transport.

Considering the approach and the additional work required, we won't be able to take the proposed changes as part of the product but would love to see this released and can support you with any changes you require to make that happen.

Would you be able to drive this forward and release as an independent package, from your own repo? We can iterate on the changes we need to have in the Worker to make that happen.

Let us know how you want to proceed, sorry about the delayed response and thank you so much for sending this!

**Comment by akamud** [comment]
Hi @fabiocav, I'm interested in understanding what are the changes you mentioned from @brettsam, is it public?

**Comment by fabiocav** [comment]
@akamud Brett was working on some of that here (early/partial): https://github.com/Azure/azure-functions-dotnet-worker/tree/brettsam/testworker

**Comment by fabiocav** [comment]
@bhugot closing this, but please let us know how we can help you move this forward if that's something you'd like to do.

Thank you again!

**Pull request closed without merging**
