### PR TITLE
Update release_notes.md

### PR DESCRIPTION
**Pull request by kshyju**
Update release notes.

### CODE REVIEW

**Review by SeanFeldman — COMMENTED** [review]
> - APIs for reading and updating input binding data, output binding data and invocation result.(#814)
> - Startup hook for extensions. (#830)
> - Exposing FunctionInputConverterException and FunctionWorkerException. (#843)
> - Adding UseWhen extension methods for middleware registration. (#865)

Would be really great to link these to the documentation or documentation PRs.

**Review by satvu — APPROVED** [review]

**Comment by kshyju** [comment]
> > * APIs for reading and updating input binding data, output binding data and invocation result.(#814)
> > * Startup hook for extensions. (#830)
> > * Exposing FunctionInputConverterException and FunctionWorkerException. (#843)
> > * Adding UseWhen extension methods for middleware registration. (#865)
> 
> Would be really great to link these to the documentation or documentation PRs.

That is in a different repo. I will make sure to share the link as soon as it is ready.

**Pull request merged**
