### PR TITLE
Updating sample projects to V4 & Net 6.0

### PR DESCRIPTION
**Pull request by kshyju**
Updating sample projects to V4 & Net 6.0.
There is one more project (net5-entity-frameowork). I will update this later.

### CODE REVIEW

**Review by satvu — APPROVED** [review]

**Comment by satvu** [comment]
There's also the [E2E Test App](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/test/E2ETests/E2EApps/E2EApp/E2EApp.csproj) but that may be more involved?

**Review by fabiocav — APPROVED** [review]

**Comment by kshyju** [comment]
> There's also the [E2E Test App](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/test/E2ETests/E2EApps/E2EApp/E2EApp.csproj) but that may be more involved?

Yea. I will address that separate.

**Pull request merged**
