### PR TITLE
Handle worker indexing property in worker.config file in Net Framework

### PR DESCRIPTION
**Pull request by satvu**
### Issue describing the changes in this PR

Fix handling of worker indexing field in the worker.config.json file for .NET Framework.

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
  * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Review by liliankasem — APPROVED** [review]

**Comment by liliankasem** [comment]
@kshyju let me know if you're able to get a release in today but no rush 😄

**Review by kshyju — APPROVED** [review]

**Comment by kshyju** [comment]
Package version bump?

**Pull request merged**
