### PR TITLE
Add overload of ConfigureFunctionsWebApplication allowing to pass HostBuilderContext in configure action

### LINKED ISSUE #1919: Add possibility to access HostBuilderContext on ConfigureFunctionsWebApplication
As `ConfigureFunctionsWebApplication` should replace `ConfigureFunctionsWorkerDefaults`, when using ASP.NET Core integration, `ConfigureFunctionsWebApplication` should have an overload receiving `Action<HostBuilderContext, IFunctionsWorkerApplicationBuilder>`.

In my case I specifically need access to `HostBuilderContext`, so that I can access the `HostBuilderContext.Configuration`

### PR DESCRIPTION
**Pull request by vmcbaptista**
### Issue describing the changes in this PR

resolves #1919

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
  * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Review by satvu — APPROVED** [review]

**Review by surgupta-msft — CHANGES_REQUESTED** [review]
Please complete the "pull request checklist" in the PR description. Also, would be helpful if you can add some tests for these changes. Thanks!

**Comment by vmcbaptista** [comment]
> Please complete the "pull request checklist" in the PR description. Also, would be helpful if you can add some tests for these changes. Thanks!

Hey!
Regarding the checklist I got some doubts:

 My changes do not require documentation changes -> I'm not sure if there's any documentation for this, if there is can you please guide me to where I should update it?
 My changes should not be added to the release notes for the next release -> I leave to the team the decision either this change is worth to be present on release notes or not, in case yes, just let me know and I would add one
 I have added all required tests (Unit tests, E2E tests) -> from what I saw, there aren't any tests regarding these extensions, that's why I didn't add any tests

**Comment by surgupta-msft** [comment]
> I have added all required tests (Unit tests, E2E tests) -> from what I saw, there aren't any tests regarding these extensions, that's why I didn't add any tests

We have extensions related tests [here](https://github.com/Azure/azure-functions-dotnet-worker/tree/main/test). If you have some test scenarios to add, you can also add them to a new project. During review, we can help consolidating/refactoring them as needed.

**Comment by vmcbaptista** [comment]
> We have extensions related tests [here](https://github.com/Azure/azure-functions-dotnet-worker/tree/main/test). If you have some test scenarios to add, you can also add them to a new project. During review, we can help consolidating/refactoring them as needed.

I've added a new test project and some unit tests, must say that adding unit tests for this is not trivial, I did my best to have a bit of coverage on the changes I made.

Regarding the two other points on checklist (documentation and release notes), do I need to do anything?

**Comment by fabiocav** [comment]
@vmcbaptista thank you for the contribution! The documentation will be auto-generated using the XML docs added. 

We can update the release notes for this change.

**Review by fabiocav — APPROVED** [review]

**Review by surgupta-msft — APPROVED** [review]

**Comment by fabiocav** [comment]
@satvu / @brettsam / @surgupta-msft  we need to make sure CI is set to run the new tests. We can pull this into a branch to enable that. The paths for the pipeline also need to be updated to include them.

**Comment by fabiocav** [comment]
Will get this in and update the CI configuration. 

Thank you, @vmcbaptista !

**Pull request merged**
