### PR TITLE
Handle route prefix with comments

### LINKED ISSUE #2707: Azure Functions with ASP.NET Core Fails to Read appsettings with Comments, Causing System.Text.Json.JsonReaderException
### Description

When integrating isolated Azure Functions with ASP.NET Core, all HTTP triggered functions fail with ` 500 `due to a `System.Text.Json.JsonReaderException`. This exception occurs when comments are present in the appsettings configuration files, exception occurs at `Worker.Extensions.Http.AspNetCore/src/AspNetMiddleware/FunctionsEndpointDataSource.cs:135`

Removing comments from the appsettings configuration files resolves the issue

Platform: Linux Ubuntu

### Steps to reproduce

Set up a project with isolated Azure Functions and integrate it with ASP.NET Core.

Use appsettings configuration files that contain comments.

Run the project and try to access any HTTP triggered functions.

### PR DESCRIPTION
**Pull request by BigDyma**
### Issue describing the changes in this PR

resolves #2707

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
  * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

Additional PR information

### CODE REVIEW

**Comment by BigDyma** [comment]
@microsoft-github-policy-service agree

**Comment by satvu** [comment]
@BigDyma can you merge main into your branch? [This change](https://github.com/Azure/azure-functions-dotnet-worker/commit/97e7048bf26b7da6d159a2c9143f42f8f91a7ef9) needs to be present to run the pipeline correctly. Thanks!

**Pull request closed without merging**
