### PR TITLE
Use current thread for handling invocation result

### PR DESCRIPTION
**Pull request by cgillum**
This PR accomplishes two things:

1. Fixes a compatibility problem with Durable Functions
2. Minor performance improvement for all function invocations in the .NET worker

The fix is simple, use the invoker thread to return the function return value instead of doing so on a worker pool thread. It's probably easier to just look at the code change.

### Issue describing the changes in this PR

One of the rules for orchestrator functions is that they must never do an `await` that would cause the callback to run on a background thread. In other words, all logic MUST run on a single thread. This includes any code that lives in the middleware pipeline between the Durable middleware and the actual function execution.

When debugging the Durable code, I observed behavior that was consistent with an "illegal await" in the function execution pipeline. I debugged the issue with @kshyju, I realized that the problem was in the DefaultFunctionInvoker. Specifically, it's using a `.ContinueWith(t => t.Result)` to convert a `Task<T>` into a `Task<object>`. It's a little strange to do it this way but there's an unfortunate side effect which is that the `t => t.Result` callback gets queued up on a worker pool thread by default. This is bad because it violates the Durable rules and also because of the unnecessary performance overhead of thread switching for something as simple as casting from one type to another.

My fix forces the callback to run on the main invoker thread, rather than scheduling it on a worker pool thread. I verified that this unblocks the Durable Functions integration work.

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
  * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Comment by fabiocav** [comment]
Change looks good, but can you please rebase on mean to clean up the commits?

**Comment by cgillum** [comment]
Won't "Squash and merge" clean up all the commits for me? I can do the rebase, but it's just a lot more work.

**Review by fabiocav — APPROVED** [review]
Yeah, this should have been there from the beginning. 

About this:

>My fix forces the callback to run on the main invoker thread, rather than scheduling it on a worker pool thread. I verified that this unblocks the Durable Functions integration work.

This might be what you meant by the above, but for clarity, to make sure that was the intention, and it would meet your requirements, this will not cause the continuation to execute on the main invoker thread, but in the same thread the original task completed. I'm assuming that meets your requirements based on the fact that you've validated, but if the `InvokeAsync` call actually goes async, the continuation would execute on the thread pool thread used for the previous task completion.

If that is the intention, might be good to update the commit description, but either way, it's a good change.

**Comment by cgillum** [comment]
You’re right. My comment is true for orchestration triggers but not necessarily for other trigger types where the function can freely go async.

**Pull request merged**
