### PR TITLE
Snippets updates

### PR DESCRIPTION
**Pull request by ggailey777**

### CODE REVIEW

**Comment by fabiocav** [comment]
@ggailey777 FYI, for now, if you want to trigger full CI, opening from a branch (e.g. `ggailey777/<name>`) instead of a fork would do that for you

**Comment by fabiocav** [comment]
I've actually updated the pipeline, so no need to change

**Comment by ggailey777** [comment]
@fabiocav these snippet updates are ready to go.
Do we need to do the /azp run thing again?

**Comment by ggailey777** [comment]
@fabiocav let me know when this gets merged and I'll submit my corresponding PR into docs.

**Review by fabiocav — APPROVED** [review]

**Comment by fabiocav** [comment]
Done

**Pull request merged**
